@startuml
left to right direction

[*] --> Identified
state "Data Identified" as Identified
state "Partially Identifiable" as Identifiable
state "De-Identified" as DeIdentified
state "Fully Anonymized" as Anonymized

Identified --> Identifiable
Identifiable --> DeIdentified
DeIdentified --> Anonymized
Anonymized --> [*]

@enduml