@startuml
left to right direction

[*] --> Identified
state "Identified" as Identified
state "Reversible-Pseudonymized" as Identifiable
state "Irreversibly Pseudonymized" as DeIdentified
state "Anonymized" as Anonymized

Identified --> Identifiable
Identifiable --> DeIdentified
DeIdentified --> Anonymized
Anonymized --> [*]

@enduml
