baseurl: "."
plugins:
  - jekyll-plantuml
  - jekyll-scholar
plantuml:
  plantuml_jar: "/opt/local/share/java/plantuml/plantuml.jar"
scholar:
  style: apa  #  APA style
  bibliography: references.bib  # default BibTeX file
kramdown:
  toc_levels: 1..3